INSERT INTO Users VALUES (1,"Donald","Duck","1313 Webfoot Walk, Duckburg, Calisota");
INSERT INTO Users VALUES (2,"Peter","Griffin","31 Spooner St, Quahog, RI");
INSERT INTO Users VALUES (3,"Brian","Griffin","31 Spooner St, Quahog, RI");
INSERT INTO Users VALUES (4,"Hank","Hill","84 Rainey St, Arlen, TX");
INSERT INTO Users VALUES (5,"Sheldon","Cooper","2311 Los Robles Ave, Pasadena, CA");
INSERT INTO Users VALUES (6,"Sherlock","Holmes","221B Baker St, London, UK");
INSERT INTO Users VALUES (7,"Stan","Smith","416 Cherry St, Langley Falls, VA");
INSERT INTO Users VALUES (8,"Spongebob","SquarePants","124 Conch St, Bikini Bottom");
INSERT INTO Users VALUES (9,"Walter","White","308 Negra Arroyo Lane, Albuquerque, NM");
INSERT INTO Users VALUES (10,"Homer","Simpson","1000 Mammon Lane, Springfield, NE");
INSERT INTO Users VALUES (11,"Monica","Geller","425 Grove St, Apt 20 , New York, NY");
INSERT INTO Users VALUES (12,"Clark","Kent","1938 Sulivan Ln, Metropolis, USA");
INSERT INTO Users VALUES (13,"Lois","Lane","1938 Sulivan Ln, Metropolis, USA");